apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ui-app"
  template:
    metadata:
      labels:
        app: "ui-app"
        instance: "live"
        deployment: "green"
    spec:
      containers:
      - name: ui-app
        image: localhost/delta-dental-ui:v2 #latest #gcr.io/google-samples/gb-frontend:v5
        ports:
        - containerPort: 80
